//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}calcName"/>
 *         &lt;element ref="{}startIonNum"/>
 *         &lt;element ref="{}endIonNum"/>
 *         &lt;element ref="{}maxShellNum"/>
 *         &lt;element ref="{}atom"/>
 *       &lt;/sequence>
 *       &lt;attribute name="calcId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "calcName",
    "startIonNum",
    "endIonNum",
    "maxShellNum",
    "atom"
})
@XmlRootElement(name = "calc")
public class Calc {

    @XmlElement(required = true)
    protected String calcName;
    @XmlSchemaType(name = "unsignedByte")
    protected short startIonNum;
    @XmlSchemaType(name = "unsignedByte")
    protected short endIonNum;
    @XmlSchemaType(name = "unsignedByte")
    protected short maxShellNum;
    @XmlElement(required = true)
    protected Atom atom;
    @XmlAttribute(required = true)
    protected int calcId;

    /**
     * Gets the value of the calcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalcName() {
        return calcName;
    }

    /**
     * Sets the value of the calcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalcName(String value) {
        this.calcName = value;
    }

    /**
     * Gets the value of the startIonNum property.
     * 
     */
    public short getStartIonNum() {
        return startIonNum;
    }

    /**
     * Sets the value of the startIonNum property.
     * 
     */
    public void setStartIonNum(short value) {
        this.startIonNum = value;
    }

    /**
     * Gets the value of the endIonNum property.
     * 
     */
    public short getEndIonNum() {
        return endIonNum;
    }

    /**
     * Sets the value of the endIonNum property.
     * 
     */
    public void setEndIonNum(short value) {
        this.endIonNum = value;
    }

    /**
     * Gets the value of the maxShellNum property.
     * 
     */
    public short getMaxShellNum() {
        return maxShellNum;
    }

    /**
     * Sets the value of the maxShellNum property.
     * 
     */
    public void setMaxShellNum(short value) {
        this.maxShellNum = value;
    }

    /**
     * Gets the value of the atom property.
     * 
     * @return
     *     possible object is
     *     {@link Atom }
     *     
     */
    public Atom getAtom() {
        return atom;
    }

    /**
     * Sets the value of the atom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atom }
     *     
     */
    public void setAtom(Atom value) {
        this.atom = value;
    }

    /**
     * Gets the value of the calcId property.
     * 
     */
    public int getCalcId() {
        return calcId;
    }

    /**
     * Sets the value of the calcId property.
     * 
     */
    public void setCalcId(int value) {
        this.calcId = value;
    }

}
