//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}source"/>
 *         &lt;element ref="{}target"/>
 *         &lt;element ref="{}threshold"/>
 *         &lt;element ref="{}fit"/>
 *         &lt;element ref="{}ciPoint" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="jumpId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "target",
    "threshold",
    "fit",
    "ciPoint"
})
@XmlRootElement(name = "ciJump")
public class CiJump {

    protected int source;
    protected int target;
    protected double threshold;
    @XmlElement(required = true)
    protected Fit fit;
    @XmlElement(required = true)
    protected List<CiPoint> ciPoint;
    @XmlAttribute(required = true)
    protected int jumpId;

    /**
     * Gets the value of the source property.
     * 
     */
    public int getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     */
    public void setSource(int value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     */
    public int getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     */
    public void setTarget(int value) {
        this.target = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     */
    public double getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     */
    public void setThreshold(double value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the fit property.
     * 
     * @return
     *     possible object is
     *     {@link Fit }
     *     
     */
    public Fit getFit() {
        return fit;
    }

    /**
     * Sets the value of the fit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fit }
     *     
     */
    public void setFit(Fit value) {
        this.fit = value;
    }

    /**
     * Gets the value of the ciPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCiPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CiPoint }
     * 
     * 
     */
    public List<CiPoint> getCiPoint() {
        if (ciPoint == null) {
            ciPoint = new ArrayList<CiPoint>();
        }
        return this.ciPoint;
    }

    /**
     * Gets the value of the jumpId property.
     * 
     */
    public int getJumpId() {
        return jumpId;
    }

    /**
     * Sets the value of the jumpId property.
     * 
     */
    public void setJumpId(int value) {
        this.jumpId = value;
    }

}
