//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pointEnergy"/>
 *         &lt;element ref="{}crossValue"/>
 *         &lt;element ref="{}collStrengthValue"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pointNum" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pointEnergy",
    "crossValue",
    "collStrengthValue"
})
@XmlRootElement(name = "ciPoint")
public class CiPoint {

    protected double pointEnergy;
    protected double crossValue;
    protected double collStrengthValue;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short pointNum;

    /**
     * Gets the value of the pointEnergy property.
     * 
     */
    public double getPointEnergy() {
        return pointEnergy;
    }

    /**
     * Sets the value of the pointEnergy property.
     * 
     */
    public void setPointEnergy(double value) {
        this.pointEnergy = value;
    }

    /**
     * Gets the value of the crossValue property.
     * 
     */
    public double getCrossValue() {
        return crossValue;
    }

    /**
     * Sets the value of the crossValue property.
     * 
     */
    public void setCrossValue(double value) {
        this.crossValue = value;
    }

    /**
     * Gets the value of the collStrengthValue property.
     * 
     */
    public double getCollStrengthValue() {
        return collStrengthValue;
    }

    /**
     * Sets the value of the collStrengthValue property.
     * 
     */
    public void setCollStrengthValue(double value) {
        this.collStrengthValue = value;
    }

    /**
     * Gets the value of the pointNum property.
     * 
     */
    public short getPointNum() {
        return pointNum;
    }

    /**
     * Sets the value of the pointNum property.
     * 
     */
    public void setPointNum(short value) {
        this.pointNum = value;
    }

}
