package db;

public enum TABLE 
{
    USERS,
    PROJECTS,
    FITTING_METHODS,
    ELEMENTS,
    IONS,
    FAC_IONS,
    NIST_LEVELS,
    LEVELS,
    NIST_TRANSITIONS,
    EXAB_TRANSITIONS,
    I_TRANSITIONS,
    AI_TRANSITIONS,
    CI_CS_FITS,
    CI_CS_POINTS,
    PI_CS_FITS,
    PI_CS_POINTS,
    EX_CS_FITS,
    EX_CS_POINTS,
    ION_STATES,
    CONFIGURATIONS,
    PLASMAS,
    LEVEL_RATES,
    IONIZATION_RATES,
    EXCITATION_RATES,
    IONS_DISTRIBUTION
}
