//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}atomName"/>
 *         &lt;element ref="{}atomSymbol"/>
 *         &lt;element ref="{}atomWeight"/>
 *         &lt;element ref="{}ion" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="atomNum" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atomName",
    "atomSymbol",
    "atomWeight",
    "ion"
})
@XmlRootElement(name = "atom")
public class Atom {

    @XmlElement(required = true)
    protected String atomName;
    @XmlElement(required = true)
    protected String atomSymbol;
    protected double atomWeight;
    @XmlElement(required = true)
    protected List<Ion> ion;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short atomNum;

    /**
     * Gets the value of the atomName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtomName() {
        return atomName;
    }

    /**
     * Sets the value of the atomName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtomName(String value) {
        this.atomName = value;
    }

    /**
     * Gets the value of the atomSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtomSymbol() {
        return atomSymbol;
    }

    /**
     * Sets the value of the atomSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtomSymbol(String value) {
        this.atomSymbol = value;
    }

    /**
     * Gets the value of the atomWeight property.
     * 
     */
    public double getAtomWeight() {
        return atomWeight;
    }

    /**
     * Sets the value of the atomWeight property.
     * 
     */
    public void setAtomWeight(double value) {
        this.atomWeight = value;
    }

    /**
     * Gets the value of the ion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ion }
     * 
     * 
     */
    public List<Ion> getIon() {
        if (ion == null) {
            ion = new ArrayList<Ion>();
        }
        return this.ion;
    }

    /**
     * Gets the value of the atomNum property.
     * 
     */
    public short getAtomNum() {
        return atomNum;
    }

    /**
     * Sets the value of the atomNum property.
     * 
     */
    public void setAtomNum(short value) {
        this.atomNum = value;
    }

}
