//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}potential"/>
 *         &lt;element ref="{}scaleFactor"/>
 *         &lt;element ref="{}fac"/>
 *         &lt;element ref="{}nist"/>
 *       &lt;/sequence>
 *       &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "potential",
    "scaleFactor",
    "fac",
    "nist"
})
@XmlRootElement(name = "ion")
public class Ion {

    protected double potential;
    @XmlSchemaType(name = "unsignedByte")
    protected short scaleFactor;
    @XmlElement(required = true)
    protected Fac fac;
    @XmlElement(required = true)
    protected Nist nist;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short charge;

    /**
     * Gets the value of the potential property.
     * 
     */
    public double getPotential() {
        return potential;
    }

    /**
     * Sets the value of the potential property.
     * 
     */
    public void setPotential(double value) {
        this.potential = value;
    }

    /**
     * Gets the value of the scaleFactor property.
     * 
     */
    public short getScaleFactor() {
        return scaleFactor;
    }

    /**
     * Sets the value of the scaleFactor property.
     * 
     */
    public void setScaleFactor(short value) {
        this.scaleFactor = value;
    }

    /**
     * Gets the value of the fac property.
     * 
     * @return
     *     possible object is
     *     {@link Fac }
     *     
     */
    public Fac getFac() {
        return fac;
    }

    /**
     * Sets the value of the fac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fac }
     *     
     */
    public void setFac(Fac value) {
        this.fac = value;
    }

    /**
     * Gets the value of the nist property.
     * 
     * @return
     *     possible object is
     *     {@link Nist }
     *     
     */
    public Nist getNist() {
        return nist;
    }

    /**
     * Sets the value of the nist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nist }
     *     
     */
    public void setNist(Nist value) {
        this.nist = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     */
    public short getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     */
    public void setCharge(short value) {
        this.charge = value;
    }

}
