//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lineSource"/>
 *         &lt;element ref="{}lineTarget"/>
 *         &lt;element ref="{}lineWavelength"/>
 *         &lt;element ref="{}lineEinstein"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineSource",
    "lineTarget",
    "lineWavelength",
    "lineEinstein"
})
@XmlRootElement(name = "line")
public class Line {

    protected int lineSource;
    protected int lineTarget;
    protected double lineWavelength;
    protected double lineEinstein;

    /**
     * Gets the value of the lineSource property.
     * 
     */
    public int getLineSource() {
        return lineSource;
    }

    /**
     * Sets the value of the lineSource property.
     * 
     */
    public void setLineSource(int value) {
        this.lineSource = value;
    }

    /**
     * Gets the value of the lineTarget property.
     * 
     */
    public int getLineTarget() {
        return lineTarget;
    }

    /**
     * Sets the value of the lineTarget property.
     * 
     */
    public void setLineTarget(int value) {
        this.lineTarget = value;
    }

    /**
     * Gets the value of the lineWavelength property.
     * 
     */
    public double getLineWavelength() {
        return lineWavelength;
    }

    /**
     * Sets the value of the lineWavelength property.
     * 
     */
    public void setLineWavelength(double value) {
        this.lineWavelength = value;
    }

    /**
     * Gets the value of the lineEinstein property.
     * 
     */
    public double getLineEinstein() {
        return lineEinstein;
    }

    /**
     * Sets the value of the lineEinstein property.
     * 
     */
    public void setLineEinstein(double value) {
        this.lineEinstein = value;
    }

}
