//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.31 at 09:49:45 AM VET 
//


package response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}stateNum"/>
 *         &lt;element ref="{}stateConfig"/>
 *         &lt;element ref="{}crmConfig"/>
 *         &lt;element ref="{}term"/>
 *         &lt;element ref="{}stateG"/>
 *         &lt;element ref="{}stateEnergy"/>
 *         &lt;element ref="{}line" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="stateId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stateNum",
    "stateConfig",
    "crmConfig",
    "term",
    "stateG",
    "stateEnergy",
    "line"
})
@XmlRootElement(name = "state")
public class State {

    protected int stateNum;
    @XmlElement(required = true)
    protected String stateConfig;
    @XmlElement(required = true)
    protected String crmConfig;
    @XmlElement(required = true)
    protected String term;
    @XmlSchemaType(name = "unsignedByte")
    protected short stateG;
    protected double stateEnergy;
    @XmlElement(required = true)
    protected List<Line> line;
    @XmlAttribute(required = true)
    protected int stateId;

    /**
     * Gets the value of the stateNum property.
     * 
     */
    public int getStateNum() {
        return stateNum;
    }

    /**
     * Sets the value of the stateNum property.
     * 
     */
    public void setStateNum(int value) {
        this.stateNum = value;
    }

    /**
     * Gets the value of the stateConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateConfig() {
        return stateConfig;
    }

    /**
     * Sets the value of the stateConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateConfig(String value) {
        this.stateConfig = value;
    }

    /**
     * Gets the value of the crmConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrmConfig() {
        return crmConfig;
    }

    /**
     * Sets the value of the crmConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrmConfig(String value) {
        this.crmConfig = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the stateG property.
     * 
     */
    public short getStateG() {
        return stateG;
    }

    /**
     * Sets the value of the stateG property.
     * 
     */
    public void setStateG(short value) {
        this.stateG = value;
    }

    /**
     * Gets the value of the stateEnergy property.
     * 
     */
    public double getStateEnergy() {
        return stateEnergy;
    }

    /**
     * Sets the value of the stateEnergy property.
     * 
     */
    public void setStateEnergy(double value) {
        this.stateEnergy = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Line }
     * 
     * 
     */
    public List<Line> getLine() {
        if (line == null) {
            line = new ArrayList<Line>();
        }
        return this.line;
    }

    /**
     * Gets the value of the stateId property.
     * 
     */
    public int getStateId() {
        return stateId;
    }

    /**
     * Sets the value of the stateId property.
     * 
     */
    public void setStateId(int value) {
        this.stateId = value;
    }

}
