//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.01 at 09:12:46 PM GMT+02:00 
//


package crm.xml.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ralchenko" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fisher" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "view")
public class View {

    @XmlAttribute(required = true)
    protected String ralchenko;
    @XmlAttribute(required = true)
    protected String fisher;

    /**
     * Gets the value of the ralchenko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRalchenko() {
        return ralchenko;
    }

    /**
     * Sets the value of the ralchenko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRalchenko(String value) {
        this.ralchenko = value;
    }

    /**
     * Gets the value of the fisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFisher() {
        return fisher;
    }

    /**
     * Sets the value of the fisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFisher(String value) {
        this.fisher = value;
    }

}
